FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Vitrius

Vitrius API specification

## Feed [/feed]

### List all investments and articles [GET]

Get application feed.

+ Response 200 (application/json)

        {
          "data": {
            "investments": [
              {
                "id": 1,
                "name": "Lamborghini",
                "positionsNumber": 1,
                "newEventsNumber": 2,
                "invitation": {
                  "id": 1,
                  "date": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                  "additionalPositionsNumber:": 1
                },
                "events": [
                  {
                    "type": "ownership",
                    "subtype": "distribution",
                    "status": "read",
                    "date": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event",
                    "amounts": [
                      {
                        "currency": "USD",
                        "value": 1234.23
                      },
                      {
                        "currency": "EUR",
                        "value": 1034.23
                      }
                    ],
                    "payDate": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                    "notes": "<p>Forwardnij mi ten raport. Mam dla ciebie gud edwajs – odpal sobie kotka na jutubie i od razu poczujesz, że możesz zrobić wszystko.</p>"
                  },
                  {
                    "type": "ownership",
                    "subtype": "capitalcall",
                    "status": "read",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event",
                    "amounts": [
                      {
                        "currency": "USD",
                        "value": 1234.23
                      },
                      {
                        "currency": "EUR",
                        "value": 1034.23
                      }
                    ],
                    "payDate": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                    "notes": "<p>Forwardnij mi ten raport. Mam dla ciebie gud edwajs – odpal sobie kotka na jutubie i od razu poczujesz, że możesz zrobić wszystko.</p>"
                  },
                  {
                    "type": "ownership",
                    "subtype": "valuation",
                    "status": "cancelled",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event"
                  },
                  {
                    "type": "voting",
                    "status": "read",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "isLive": true,
                    "name": "Name of the event",
                    "schedule": [
                      {
                        "name": "Meeting date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      },
                      {
                        "name": "Opening date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      },
                      {
                        "name": "Closing date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      }
                    ],
                    "labels": [
                      "attend",
                      "proxyvoting"
                    ],
                    "locationName": "HQs",
                    "address": [
                      "Herengracht 180",
                      "1016BR Amsterdam",
                      "Netherlands"
                    ]
                  },
                  {
                    "type": "reporting",
                    "status": "unread",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event"
                  },
                  {
                    "type": "Data Room",
                    "status": "unread",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "documents": [
                      {
                        "name": "Document1",
                        "url": "https://vitrius.co/documents/doc.png",
                        "year": 2015,
                        "tags": [
                          "Tag 1",
                          "Tag 2"
                        ]
                      },
                      {
                        "name": "Document2",
                        "url": "https://vitrius.co/documents/doc.png",
                        "year": 2015,
                        "tags": [
                          "Tag 2",
                          "Tag 3"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": 2,
                "name": "Starbucks",
                "positionsNumber": 3,
                "newEventsNumber": 1,
                "invitation": null,
                "events": []
              },
              {
                "id": 3,
                "name": "GreenTowers",
                "positionsNumber": 2,
                "newEventsNumber": 0,
                "invitation": null,
                "events": []
              },
              {
                "id": 4,
                "name": "MacLaren",
                "positionsNumber": 0,
                "newEventsNumber": 0,
                "invitation": {
                  "id": 2,
                  "date": "date",
                  "additionalPositionsNumber:": 1
                },
                "events": []
              }
            ],
            "articles": [
              {
                "investment": {
                  "id": 1,
                  "name": "Lamborghini"
                },
                "title": "Title of the first article",
                "date": {
                  "timestamp": 1446146162,
                  "timezone": "Europe/Warsaw"
                }
              },
              {
                "investment": {
                  "id": 2,
                  "name": "Starbucks"
                },
                "title": "Title of the second article",
                "date": {
                  "timestamp": 1446146162,
                  "timezone": "Europe/Warsaw"
                }
              }
            ]
          },
          "errors": null
        }


+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }
        

## Article details [/articles/{id}]

+ Parameters
    + id - article id

### GET Article details [GET]

Get article details.

+ Response 200 (application/json)

        {
          "data": {
            "investment": {
              "id": 1,
              "name": "Lamborghini"
            },
            "title": "Title of the first article",
            "date": {
              "timestamp": 1446146162,
              "timezone": "Europe/Warsaw"
            },
            "author": "John Smith",
            "images": [
              {
                "width": 800,
                "height": 450,
                "url": "https://vitrius.co/images/doc.png"
              },
              {
                "width": 800,
                "height": 450,
                "url": "https://vitrius.co/images/doc.png"
              }
            ],
            "content": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer egestas lacinia orci in pellentesque. Duis quam tortor, dictum at tincidunt vel, egestas eget tellus. Maecenas nibh orci, fermentum at rhoncus quis, consequat non sapien. Sed sit amet tempus mauris, auctor suscipit leo.</p>"
          },
          "errors": null
        }


## Investment invitation acceptance [/invitationAcceptance/]

### POST Investment invitation acceptance [POST]

+ Request (application/json)

        {
            "invitationId": 1
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "status_code": 200
            },
            "errors": null
        }
        
+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }
        
## Application invitation sending [/appInvitation/]

### POST Investment invitation sending [POST]

+ Request (application/json)

        {
            "email": "test@jojomobile.pl"
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "status_code": 200
            },
            "errors": null
        }
        
+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }
## Event status change to "read" [/eventRead/]

### POST to change event status to "read" [POST]

+ Request (application/json)

        {
            "eventId": 1
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "status_code": 200
            },
            "errors": null
        }

+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }
        
## Token Autorization [/tokenAutorization/]

### POST autorization token to autorize app [POST]

+ Request (application/json)

        {
            "token": 1234567890ABCDEFGHIJKMNOPRSTUWXYZ
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "status_code": 200
            },
            "errors": null
        }

+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }