FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Vitrius

Vitrius API specification

## Feed [/feed]

### List all investments and articles [GET]

Get application feed.

+ Response 200 (application/json)

        
        {
          "data": {
            "user": {
                "email": "support@vitrius.co",
                "hash": "514a8581f5549c6b547"
            },
            "investments": [
              {
                "id": 1,
                "name": "Lamborghini",
                "positionsNumber": 1,
                "newEventsNumber": 2,
                "invitation": {
                  "id": 1,
                  "date": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                  "additionalPositionsNumber": 1,
                  "name": "Accept position for new found"
                },
                "events": [
                  {
                    "id": 1,
                    "type": "ownership",
                    "subtype": "distribution",
                    "status": "read",
                    "date": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event",
                    "amounts": [
                      {
                        "currency": "USD",
                        "value": 1234.23
                      },
                      {
                        "currency": "EUR",
                        "value": 1034.23
                      }
                    ],
                    "payDate": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                    "notes": "<p>Forwardnij mi ten raport. Mam dla ciebie gud edwajs – odpal sobie kotka na jutubie i od razu poczujesz, że możesz zrobić wszystko.</p>"
                  },
                  {
                    "id": 2,
                    "type": "ownership",
                    "subtype": "capitalcall",
                    "status": "read",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event",
                    "amounts": [
                      {
                        "currency": "USD",
                        "value": 1234.23
                      },
                      {
                        "currency": "EUR",
                        "value": 1034.23
                      }
                    ],
                    "payDate": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                    "notes": "<p>Forwardnij mi ten raport. Mam dla ciebie gud edwajs – odpal sobie kotka na jutubie i od razu poczujesz, że możesz zrobić wszystko.</p>"
                  },
                  {
                    "id": 3,  
                    "type": "ownership",
                    "subtype": "valuation",
                    "status": "cancelled",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event",
                    "amounts": [
                      {
                        "currency": "USD",
                        "value": 1234.23
                      },
                      {
                        "currency": "EUR",
                        "value": 1034.23
                      }
                    ]
                  },
                  {
                    "id": 4, 
                    "type": "voting",
                    "status": "read",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "isLive": true,
                    "name": "Name of the event",
                    "schedule": [
                      {
                        "name": "Meeting date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      },
                      {
                        "name": "Opening date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      },
                      {
                        "name": "Closing date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      }
                    ],
                    "labels": [
                      "attend",
                      "proxyvoting"
                    ],
                    "locationName": "HQs",
                    "address": [
                      "Herengracht 180",
                      "1016BR Amsterdam",
                      "Netherlands"
                    ]
                  },
                  {
                    "id": 5, 
                    "type": "reporting",
                    "status": "unread",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event"
                  },
                  {
                    "id": 6, 
                    "type": "data room",
                    "status": "unread",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "documents": [
                      {
                        "name": "Document1",
                        "url": "https://vitrius.co/documents/doc.png",
                        "year": 2015,
                        "tags": [
                          "Tag 1",
                          "Tag 2"
                        ]
                      },
                      {
                        "name": "Document2",
                        "url": "https://vitrius.co/documents/doc.png",
                        "year": 2015,
                        "tags": [
                          "Tag 2",
                          "Tag 3"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": 2,
                "name": "Starbucks",
                "positionsNumber": 3,
                "newEventsNumber": 1,
                "invitation": null,
                "events": []
              },
              {
                "id": 3,
                "name": "TestInvestment1",
                "positionsNumber": 3,
                "newEventsNumber": 1,
                "invitation": null,
                "events": []
              },
              {
                "id": 4,
                "name": "TestInvestment2",
                "positionsNumber": 3,
                "newEventsNumber": 1,
                "invitation": null,
                "events": []
              },
              {
                "id": 5,
                "name": "TestInvestment3",
                "positionsNumber": 3,
                "newEventsNumber": 1,
                "invitation": null,
                "events": []
              },
              {
                "id": 2,
                "name": "Starbucks",
                "positionsNumber": 3,
                "newEventsNumber": 1,
                "invitation": null,
                "events": []
              },
              {
                "id": 6,
                "name": "GreenTowers",
                "positionsNumber": 2,
                "newEventsNumber": 0,
                "invitation": null,
                "events": [
                  {
                    "id": 7,
                    "type": "ownership",
                    "subtype": "distribution",
                    "status": "read",
                    "date": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event",
                    "amounts": [
                      {
                        "currency": "USD",
                        "value": 1234.23
                      },
                      {
                        "currency": "EUR",
                        "value": 1034.23
                      }
                    ],
                    "payDate": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                    "notes": "<p>Forwardnij mi ten raport. Mam dla ciebie gud edwajs – odpal sobie kotka na jutubie i od razu poczujesz, że możesz zrobić wszystko.</p>"
                  },
                  {
                    "id": 8,
                    "type": "ownership",
                    "subtype": "capitalcall",
                    "status": "read",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event",
                    "amounts": [
                      {
                        "currency": "USD",
                        "value": 1234.23
                      },
                      {
                        "currency": "EUR",
                        "value": 1034.23
                      }
                    ],
                    "payDate": {
                      "timestamp": 1446046162,
                      "timezone": "Europe/Warsaw"
                    },
                    "notes": "<p>Forwardnij mi ten raport. Mam dla ciebie gud edwajs – odpal sobie kotka na jutubie i od razu poczujesz, że możesz zrobić wszystko.</p>"
                  },
                  {
                    "id": 9,  
                    "type": "ownership",
                    "subtype": "valuation",
                    "status": "cancelled",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event",
                    "amounts": [
                      {
                        "currency": "USD",
                        "value": 1234.23
                      },
                      {
                        "currency": "EUR",
                        "value": 1034.23
                      }
                    ]
                  },
                  {
                    "id": 10, 
                    "type": "voting",
                    "subtype": "meeting",
                    "status": "read",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "isLive": true,
                    "name": "Name of the event",
                    "schedule": [
                      {
                        "name": "Meeting date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      },
                      {
                        "name": "Opening date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      },
                      {
                        "name": "Closing date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      }
                    ],
                    "labels": [
                      "attend",
                      "proxyvoting"
                    ],
                    "locationName": "HQs",
                    "address": [
                      "Herengracht 180",
                      "1016BR Amsterdam",
                      "Netherlands"
                    ]
                  },
                  {
                    "id": 11, 
                    "type": "voting",
                    "subtype": "nomeeting",
                    "status": "read",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "isLive": true,
                    "name": "Name of the event",
                    "schedule": [
                      {
                        "name": "Meeting date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      },
                      {
                        "name": "Opening date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      },
                      {
                        "name": "Closing date",
                        "date": {
                          "timestamp": 1446046162,
                          "timezone": "Europe/Warsaw"
                        }
                      }
                    ],
                    "labels": [
                      "attend",
                      "proxyvoting"
                    ],
                    "locationName": "HQs",
                    "address": [
                      "Herengracht 180",
                      "1016BR Amsterdam",
                      "Netherlands"
                    ]
                  },
                  {
                    "id": 12, 
                    "type": "reporting",
                    "status": "unread",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "name": "Name of the event"
                  },
                  {
                    "id": 13, 
                    "type": "data room",
                    "status": "unread",
                    "date": {
                      "timestamp": 1446146162,
                      "timezone": "Europe/Warsaw"
                    },
                    "documents": [
                      {
                        "name": "Document1",
                        "url": "https://vitrius.co/documents/doc.png",
                        "year": 2015,
                        "tags": [
                          "Tag 1",
                          "Tag 2"
                        ]
                      },
                      {
                        "name": "Document2",
                        "url": "https://vitrius.co/documents/doc.png",
                        "year": 2015,
                        "tags": [
                          "Tag 2",
                          "Tag 3"
                        ]
                      }
                    ]
                  }
                ]
              },
              {
                "id": 4,
                "name": "MacLaren",
                "positionsNumber": 0,
                "newEventsNumber": 0,
                "invitation": {
                  "id": 2,
                  "date": {
                    "timestamp": 1446146162,
                    "timezone": "Europe/Warsaw"
                  },
                  "additionalPositionsNumber": 1,
                  "name": "Accept position for found"
                },
                "events": []
              }
            ],
            "articles": [
              {
                "id" : 3,
                "investment": {
                  "id": 1,
                  "name": "Lamborghini"
                },
                "title": "Title of the first article",
                "date": {
                  "timestamp": 1446146162,
                  "timezone": "Europe/Warsaw"
                }
              },
              {
                "id" : 4,
                "investment": {
                  "id": 2,
                  "name": "Starbucks"
                },
                "title": "Title of the second article",
                "date": {
                  "timestamp": 1446146162,
                  "timezone": "Europe/Warsaw"
                }
              }
            ]
          },
          "errors": null
        }


+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }
        

## Article details [/articles/{id}]

+ Parameters
    + id - article id

### GET Article details [GET]

Get article details.

+ Response 200 (application/json)

        {
          "data": {
            "id" : 1,
            "investment": {
              "id": 1,
              "name": "Lamborghini"
            },
            "title": "Title of the first article",
            "date": {
              "timestamp": 1446146162,
              "timezone": "Europe/Warsaw"
            },
            "author": "John Smith",
            "images": [
              {
                "width": 800,
                "height": 450,
                "url": "https://vitrius.co/images/doc.png"
              },
              {
                "width": 800,
                "height": 450,
                "url": "https://vitrius.co/images/doc.png"
              }
            ],
            "content": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer egestas lacinia orci in pellentesque. Duis quam tortor, dictum at tincidunt vel, egestas eget tellus. Maecenas nibh orci, fermentum at rhoncus quis, consequat non sapien. Sed sit amet tempus mauris, auctor suscipit leo.</p>"
          },
          "errors": null
        }


## Investment invitation acceptance [/invitationAcceptance]

### POST Investment invitation acceptance [POST]

+ Request (application/json)

        {
            "invitationId": 1
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "status_code": 200
            },
            "errors": null
        }
        
+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }
        
## Application invitation sending [/appInvitation]

### POST Investment invitation sending [POST]

+ Request (application/json)

        {
            "email": "test@jojomobile.pl"
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "status_code": 200
            },
            "errors": null
        }
        
+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }
## Event status change to "read" [/eventRead]

### POST to change event status to "read" [POST]

+ Request (application/json)

        {
            "eventId": 1,
            "type": "voting"
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "status_code": 200
            },
            "errors": null
        }

+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }
        
## Token Autorization [/tokenAutorization/]

### POST autorization token to autorize app [POST]

+ Request (application/json)

        {
            "token": 1234567890ABCDEFGHIJKMNOPRSTUWXYZ
        }
        
+ Response 200 (application/json)

        {
            "data": {
                "status_code": 200
            },
            "errors": null
        }

+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }
        
## Token Autorization [/votingResults/]

### POST autorization token to autorize app [GET]

        
+ Response 200 (application/json)

        {
            "0":{
                "6":{
                    "id":6,
                    "bullet":"1",
                    "subject":"Opening en notulen vorige vergadering",
                    "votable":false,
                    "infavor":0,
                    "against":0,
                    "abstain":0,
                    "thresholdValue":0,
                    "shareFull":65,
                    "shareFullNoMulti":65,
                    "passed":false
                },
                "7":{
                    "id":7,
                    "bullet":"2",
                    "subject":"Directieverslag",
                    "votable":false,
                    "infavor":0,
                    "against":0,
                    "abstain":0,
                    "thresholdValue":0,
                    "shareFull":65,
                    "shareFullNoMulti":65,
                    "passed":false
                 },
                "8":{
                    "id":8,
                    "bullet":"3",
                    "subject":"Verslag Raad van Toezicht",
                    "votable":false,
                    "infavor":0,
                    "against":0,
                    "abstain":0,
                    "thresholdValue":0,
                    "shareFull":65,
                    "shareFullNoMulti":65,
                    "passed":false
                },
                "9":{
                    "id":9,
                    "bullet":"4",
                    "subject":"Jaarcijfers 2013, decharge Directie",
                    "votable":true,
                    "position":"65",
                    "infavor":2,
                    "against":63,
                    "abstain":0,
                    "total":"16.0000",
                    "thresholdValue":100,
                    "shareFull":65,
                    "shareFullNoMulti":65,
                    "passed":false
                 },
                "10":{
                    "id":10,
                    "bullet":"5",
                    "subject":"Resultaatbestemming en besluit (interim) dividend",
                    "votable":true,
                    "position":"65",
                    "infavor":5,
                    "against":0,
                    "abstain":1,
                    "total":"0.0000",
                    "thresholdValue":100,
                    "shareFull":65,
                    "shareFullNoMulti":65,
                    "passed":false
                 },
                "11":{
                    "id":11,
                    "bullet":"6",
                    "subject":"Portfolio voortgangsrapport",
                    "votable":false,
                    "infavor":0,
                    "against":0,
                    "abstain":0,
                    "thresholdValue":0,
                    "shareFull":65,
                    "shareFullNoMulti":65,
                    "passed":false
                },
                "12":{
                    "id":12,
                    "bullet":"7",
                    "subject":"Wvttk",
                    "votable":false,
                    "infavor":0,
                    "against":0,
                    "abstain":0,
                    "thresholdValue":0,
                    "shareFull":65,
                    "shareFullNoMulti":65,
                    "passed":false
                },
                "13":{
                    "id":13,
                    "bullet":"8",
                    "subject":"Sluiting",
                    "votable":false,
                    "infavor":0,
                    "against":0,
                    "abstain":0,
                    "thresholdValue":0,
                    "shareFull":65,
                    "shareFullNoMulti":65,
                    "passed":false
                }
            },
            "13":[
                    {
                        "id":6,
                        "bullet":"1",
                        "subject":"Opening en notulen vorige vergadering",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"16.0000",
                        "shareFullNoMulti":"16",
                        "passed":false
                    },
                    {
                        "id":7,
                        "bullet":"2",
                        "subject":"Directieverslag",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"16.0000",
                        "shareFullNoMulti":"16",
                        "passed":false
                    },
                    {
                        "id":8,
                        "bullet":"3",
                        "subject":"Verslag Raad van Toezicht",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"16.0000",
                        "shareFullNoMulti":"16",
                        "passed":false
                    },
                    {
                        "id":9,
                        "bullet":"4",
                        "subject":"Jaarcijfers 2013, decharge Directie",
                        "votable":true,
                        "position":"65",
                        "infavor":"0",
                        "against":"16",
                        "abstain":"0",
                        "total":"16.0000",
                        "thresholdValue":"50",
                        "shareFull":"16.0000",
                        "shareFullNoMulti":"16",
                        "passed":false
                    },
                    {
                        "id":10,
                        "bullet":"5",
                        "subject":"Resultaatbestemming en besluit (interim) dividend",
                        "votable":true,
                        "position":"65",
                        "infavor":"0",
                        "against":"0",
                        "abstain":"0",
                        "total":"0.0000",
                        "thresholdValue":"50",
                        "shareFull":"16.0000",
                        "shareFullNoMulti":"16",
                        "passed":false
                    },
                    {
                        "id":11,
                        "bullet":"6",
                        "subject":"Portfolio voortgangsrapport",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"16.0000",
                        "shareFullNoMulti":"16",
                        "passed":false
                    },
                    {
                        "id":12,
                        "bullet":"7",
                        "subject":"Wvttk",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"16.0000",
                        "shareFullNoMulti":"16",
                        "passed":false
                    },
                    {
                        "id":13,
                        "bullet":"8",
                        "subject":"Sluiting",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"16.0000",
                        "shareFullNoMulti":"16",
                        "passed":false
                    }
                ],
            "14":[
                    {
                        "id":6,
                        "bullet":"1",
                        "subject":"Opening en notulen vorige vergadering",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"49.0000",
                        "shareFullNoMulti":"49",
                        "passed":false
                    },
                    {
                        "id":7,
                        "bullet":"2",
                        "subject":"Directieverslag",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"49.0000",
                        "shareFullNoMulti":"49",
                        "passed":false
                    },
                    {
                        "id":8,
                        "bullet":"3",
                        "subject":"Verslag Raad van Toezicht",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"49.0000",
                        "shareFullNoMulti":"49",
                        "passed":false
                    },
                    {
                        "id":9,
                        "bullet":"4",
                        "subject":"Jaarcijfers 2013, decharge Directie",
                        "votable":true,
                        "position":"65",
                        "infavor":"2",
                        "against":"47",
                        "abstain":"0",
                        "total":"49.0000",
                        "thresholdValue":"50",
                        "shareFull":"49.0000",
                        "shareFullNoMulti":"49",
                        "passed":false
                    },
                    {
                        "id":10,
                        "bullet":"5",
                        "subject":"Resultaatbestemming en besluit (interim) dividend",
                        "votable":true,
                        "position":"65",
                        "infavor":"5",
                        "against":"0",
                        "abstain":"1",
                        "total":"6.0000",
                        "thresholdValue":"50",
                        "shareFull":"49.0000",
                        "shareFullNoMulti":"49",
                        "passed":true
                    },
                    {
                        "id":11,
                        "bullet":"6",
                        "subject":"Portfolio voortgangsrapport",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"49.0000",
                        "shareFullNoMulti":"49",
                        "passed":false
                    },
                    {
                        "id":12,
                        "bullet":"7",
                        "subject":"Wvttk",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"49.0000",
                        "shareFullNoMulti":"49",
                        "passed":false
                    },
                    {
                        "id":13,
                        "bullet":"8",
                        "subject":"Sluiting",
                        "votable":false,
                        "thresholdValue":"",
                        "shareFull":"49.0000",
                        "shareFullNoMulti":"49",
                        "passed":false
                    }
                ]
        }

+ Response 400 (application/json) 

        {
            "data" : null,
            "errors" : [
                {
                    "code" : 123,
                    "message" : "Invalid parameters."
                }
            ]
        }